### ISSUE TITLE
Character encoding problem after upgrade to Phoenix 1.2.1, Elixir 1.3.3

### ISSUE THREAD

**Issue by Alamoz** [elixir-ecto/ecto#1848]
* Elixir 1.3.3
* Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
* PostgreSQL 9.5.5
* ecto 2.0.6 (Hex package) (mix)
  locked at 2.0.6 (ecto) 9dcbf819
* postgrex 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (postgrex) 2f8b46cb
* Operating system: Ubuntu Server 16.04 with latest updates

Had to upgrade to Phoenix 1.2.1 to get a new controller working, and as well had to create a new app and copy my older code to it. The older code was running normally under Phoenix 1.2.0 with an app template over a year old. App is small, just a simple API serving json from a Postgres database. After creating the new app and porting my code, it works perfectly in local development mode, but on the production server the app fails to respond and in the Erlang log file for the app (app is deployed with exrm) the following error occurs:

"warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Interactive Elixir (1.3.3) - press Ctrl+C to exit (type h() ENTER for help)"

Nothing has changed on the server. The older version of the app was running perfectly. The locale is set correctly to en_US.UTF-8 both on the server and development machines. I can't fall back to the older version because the new controller won't run on it.

Also tried going back to Phoenix 1.2.0 with the new app template and experienced the same problem.

Update:  When I tried adding the new code to the old app template, it didn't work. I tried again and now it does work. So I think some dependency was munged and must have gotten fixed during one of my several "mix deps.get" tries. So I can get my new code to work with the older app template, but not with a freshly generated Phoenix 1.2.1 app template (I'm calling the app tree a "template",) when I try it has this character encoding problem.

**Comment by josevalim** [comment]
> but on the production server the app fails to respond and in the Erlang log file

Do you get any error at all besides that initial message? When you say your server fails to respond, what does it mean? Do you get a status code or nothing at all?

**Comment by Alamoz** [comment]
"Fail to respond" means no json was returned. The Phoenix app didn't crash. Using Nginx reverse proxy which is unaffected. The erlang log file in Phoenix app directory myapp/log just gives the warning I posted above:

"warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Interactive Elixir (1.3.3) - press Ctrl+C to exit (type h() ENTER for help)"

I was finally able to get my new controller working with the old version of my Phoenix app which is updated to Elixir 1.3.3 and Phoenix 1.2.1, so I'm OK with my app for now. But in the future if I create a fresh Phoenix app this could be a problem.

I always seem to hit the weird edge cases and intermittent bugs caused by version mangling, etc. I will try creating a fresh demo app and see if this problem occurs with it.

**Comment by josevalim** [comment]
Ok, thank you. At the moment it is unclear what could be happening so more information is appreciated. Btw, next time it happens, please let us know which status code is being returned. If it happens to be 400, it is probably an issue with cookies (and erasing them should solve the problem).

**Comment by Alamoz** [comment]
I will also upload the offending app again and see if an error code is returned, but I didn't see any error code.

**Comment by Alamoz** [comment]
OK, just tried again with a new Phoenix 1.2.1 app and still the same problem. The http code returned is "502 Bad Gateway." The warning message in erlang.log.1 when the app starts is still the same as I posted above.

There was a recent update to the Ubuntu 'locales' package, perhaps that is somehow involved. When I run my app with the old Phoenix template created around a year ago, this problem doesn't occur.

**Comment by josevalim** [comment]
And setting a proper locale does not fix the issue in anyway? If the error is in the generated app, then I would consider checking the encoding of Phoenix generated files. Although I believe by default everything is ASCII (unless you added something in another language).

Also, we should probably move this to Phoenix instead of Ecto, although I don't think it would make a difference without a way for us to also reproduce it. :S

Thank you!

**Comment by michalmuskala** [comment]
I wouldn't focus on the locale thing, it's just a warning.

The more troubling thing is the lack of the usual "listening on port xxx" message that is printed when endpoint starts. Are you sure you have `server: true` set in the endpoint configuration?

**Comment by josevalim** [comment]
I am closing because we need more info to reproduce and it does not sound like an Ecto issue. However, feel free to continue posting information and we will be glad to help.

**Comment by Alamoz** [comment]
Setting the proper locale does not fix the issue.
